### ISSUE TITLE
WIZnetw5300

### ISSUE THREAD

**Issue by ZHOUHENG3Q** [mhanuel26/TangNano_W5300_TOE_GOWIN#1]
Hello, has the w5300 communication module been completed

**Comment by ZHOUHENG3Q** [comment]
Thank you. Currently, your project can receive UDP data. Can I also send data? How do I need to modify it for W5300 self loopback testing? Using asynchronous FIFO IP?

**Comment by mhanuel26** [comment]
Hi @ZHOUHENG3Q , 
I am currently working to provide SEND functionality, good progress there, need to test code at the moment, I normallytest first using test bench, I expect to push my changes asap within one day or two. 
Can you wait for my changes? I will include an example for loopback as well.

**Comment by mhanuel26** [comment]
Hey @ZHOUHENG3Q , 

Still not a loopback example but I have included now the example of SEND UDP. Tested so far in ModelSim only. I will be testing in hardware and creating loopback example as well.

**Comment by mhanuel26** [comment]
Hi @ZHOUHENG3Q ,

I don't have much time available as this is a hobby stuff but I want to finish this as well asap, most probably will update during the weekend.

Cheers,

**Comment by mhanuel26** [comment]
Hey @ZHOUHENG3Q ,

I have push some changes for the loopback, it is tested so far in Modelsim. Will be  doing some tests in the next day or two on the hardware.

**Comment by ZHOUHENG3Q** [comment]
Hi, your speed is really fast, brother, I learned the W5300 Ethernet communication project from you, thank you very much

**Comment by ZHOUHENG3Q** [comment]
Hello, I am using the UDP protocol of the W5300 Ethernet chip. How to use the host computer software to send data? How to implement the FPGA to send data to the computer, and how to handle their reception?

**Comment by mhanuel26** [comment]
Hi @ZHOUHENG3Q ,

I have added a small python script that I used to test the UDP receive. I will be adding other script to test loopback.

**Comment by mhanuel26** [comment]
Hey @ZHOUHENG3Q ,

I tested loopback in the hardware. I added a small python script for testing. There is a small bug when sending odd number of bytes in the payload, but simulation looks correctly so need to investigate.

Are you testing this on your end? 

Cheers,
Manuel

**Comment by mhanuel26** [comment]
Hi @ZHOUHENG3Q , 

Loopback test in hardware is complete, also there is a loopback example for getting speed. Closing this for now.
